version: "3"
services:
  redis:
    image: redis:latest
    env_file: .env
    ports:
      - "6379:6379"
    volumes:
      - $REDIS_PATH/data:/data:rw
      - $REDIS_PATH/conf/redis.conf:/etc/redis/redis.conf:ro
  
  nginx:
    image: nginx:latest
    env_file: .env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $NGINX_PATH/nginx.conf:/etc/nginx/nginx.conf:ro
      - $NGINX_PATH:/nginx:rw
      - $WEBROOT_PATH:/www:rw

  postgres:
    image: postgres:latest
    env_file: .env
    ports: 
      - "5432:5432"
    environment:
       # provide password
       - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    volumes: 
      - $PG_PATH/conf/postgresql.conf:/etc/postgresql.conf:ro
      - $PG_PATH/data:/var/lib/postgresql/DATA:rw
      - $PG_PATH/logs:/logs:rw
    command: postgres -c logging_collector=on -c log_destination=stderr -c log_directory=/logs -c config_file=/etc/postgresql.conf
  
  httpbin:
    image: httpbin:v1
    ports:
      - "11010:80"
  
  mc:
    image: itzg/minecraft-server
    env_file: .env
    ports: 
      - "25565:25565"
      - "25575:25575"
    environment: 
      EULA: "TRUE"
      TYPE: CUSTOM
      CUSTOM_SERVER: server.jar
      FABRIC_INSTALLER: fabric-installer-0.7.3.jar
      SERVER_NAME: "A minecraft server by kun"
      DIFFICULTY: hard
      MAX_PLAYERS: 5
      MEMORY: 2G
    volumes:
      - $MC_PATH:/data
  
  jupyter:
    image: jupyter/base-notebook:python-3.8.8
    env_file: .env
    ports:
      - "11012:8888"
    volumes:
      - $JUPYTER_PATH:/home/jovyan
