version: "3"
services:
  redis:
    image: redis:latest
    env_file: .env
    ports:
      - "6379:6379"
    volumes:
      - $REDIS_PATH/data:/data:rw
      - $REDIS_PATH/conf/redis.conf:/etc/redis/redis.conf:ro
  
  nginx:
    image: nginx:latest
    env_file: .env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $NGINX_PATH:/etc/nginx:rw
      - $WEBROOT_PATH:/www:rw
